tasks = [
    "e**x",
    "ln(1+x)", 
    "(1+x)**0.5",
    "(1/(1+x))**0.5",
    "sin x",
    "cos x",
    "tg x",
    "arcsin x",
    "arccos x",
    "arctg x",
    "arcctg x",
    "sh x",
    "ch x",
    ]